project:
  type: website

website:
  title: "EcoEvoMatics Lab"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd

format:
  html:
    theme: 
        - cyborg
        - custom.scss
    fontsize: 1.5em
    linestretch: 2
    css: styles.css
    toc: true



